// docs/demos/todolist/src/index.tsx
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';

import '@appstate-fast/devtools';

import App from './App';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(<App />, document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();

// docs/demos/solid/src/index.js
import { render } from 'solid-js/web';
import './bulma.min.css'
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

render(App, document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
