// docs/demos/todolist/src/components/TasksTotal.vue
<template>
  <div style="display:flex;justify-content:space-evenly;margin-bottom:30px;">
    <div v-if="settingsState.isHighlightUpdateEnabled" style="width: 10px;marginRight:15px;"></div>
    <p v-if="tasksState.promised">Loading</p>
    <p v-else-if="tasksState.error">Error</p>
    <div v-else style="display:flex;justify-content:space-evenly;flex-grow:2;">
      <div>Loaded: {{!tasksState.promised ? "loaded" : "nope"}}</div>
    </div>
  </div>
</template>

<script>
import { ref, defineComponent } from "vue";
import { useTasksState } from "./TasksState";
import { useSettingsState } from "./SettingsState";

export default defineComponent({
  name: "TasksTotal",
  setup() {
    // Use both global stores in the same component.
    // Note: in fact, it it could be even one state object
    // with functions accessing different nested segments of the state data.
    // It would perform equally well.
    const settingsState = useSettingsState();
    const tasksState = useTasksState();

    // This is the trick to obtain different color on every run of this function
    const colors = ["#ff0000", "#00ff00", "#0000ff"];
    const color = ref(0);
    color.value += 1;
    const nextColor = colors[color.value % colors.length];

    return { tasksState, settingsState, nextColor };
  }
});
</script>

<style>
</style>

// docs/demos/todolist/src/components/TasksTotal.tsx
import React from 'react';
import { useTasksState } from './TasksState';
import { useSettingsState } from './SettingsState';
import { self } from '@appstate-fast/core';

export function TasksTotal() {
    // Use both global stores in the same component.
    // Note: in fact, it it could be even one state object
    // with functions accessing different nested segments of the state data.
    // It would perform equally well.
    const tasksState = useTasksState();
    const settingsState = useSettingsState();
    
    // This is the trick to obtain different color on every run of this function
    var colors = ['#ff0000', '#00ff00', '#0000ff'];
    const color = React.useRef(0)
    color.current += 1
    var nextColor = colors[color.current % colors.length];
    
    return <div style={{
        display: 'flex',
        justifyContent: 'space-evenly',
        marginBottom: 30
    }}>
        {settingsState.isHighlightUpdateEnabled &&
            <div
                style={{
                    width: 10,
                    marginRight: 15,
                    backgroundColor: nextColor
                }}
            />
        }
        {tasksState[self].map(
            ts => <div key="" style={{
                display: 'flex',
                justifyContent: 'space-evenly',
                flexGrow: 2
            }}>
                <div>Total tasks: {ts.length}</div>
                <div>Done: {ts.filter(i => i.done.value).length}</div>
                <div>Remaining: {ts.filter(i => !i.done.value).length}</div>
            </div>,
            () => <></> // if promised
        )}
    </div>
}
